### PR TITLE
Coffeelint integration

### PR DESCRIPTION
**Pull request by 73rhodes**
Integrates [coffeelint-ruby](https://github.com/zmbush/coffeelint-ruby) into policial.

### CODE REVIEW

**Comment by nwtn** [comment]
@73rhodes awesome! Agreed that it would be great to get this pulling the lint file from the repo automatically somehow, but this is a great first step! Re-ping when you get the tests working, I’d love to take this for a :tophat:.

**Comment by volmer** [comment]
Awesome work, @73rhodes! I fixed `StyleChecker` on master and now you have a green build :)

**Comment by volmer** [comment]
We still need to implement support for config files, but this is a great first step nonetheless. :clap:

**Comment by 73rhodes** [comment]
Cool, thanks for the help! It you have any pointers for how the config should be done let me know...

**Comment by volmer** [comment]
I'll merge right away it and then we can iterate. The configuration file you're adding is a good default and I can't wait to try it live. Thanks a lot for your work on this!

**Comment by 73rhodes** [comment]
no prob,  can't wait to try it too! and thanks for all the pointers.

**Pull request merged**
